// Single, deduplicated global industry directory for employer registration,
// company profiles, job posting, matching filters, and analytics.
export const INDUSTRY_MASTER = Array.from(new Set([
  "Information Technology (IT)", "Software & SaaS", "Banking & Financial Services", "Insurance", "Healthcare",
  "Pharmaceuticals", "Education & EdTech", "Manufacturing", "Automotive", "Construction & Infrastructure",
  "Real Estate", "Retail", "E-commerce", "Telecommunications", "Media & Entertainment", "Advertising & Marketing",
  "Consulting", "Accounting & Taxation", "Legal Services", "Hospitality & Tourism", "Food & Beverage",
  "Transportation & Logistics", "Energy & Utilities", "Oil & Gas", "Agriculture", "Government & Public Sector",
  "Aerospace & Defense", "Consumer Goods (FMCG)", "Human Resources & Recruitment", "Artificial Intelligence & Machine Learning",
  "Cybersecurity", "Cloud Computing & Data Centers", "FinTech", "HealthTech", "Biotechnology", "Medical Devices",
  "Chemicals", "Electronics & Semiconductors", "Electrical Equipment", "Industrial Automation", "Robotics",
  "Engineering Services", "Heavy Machinery & Equipment", "Metals & Mining", "Steel & Cement", "Textiles & Apparel",
  "Fashion & Luxury", "Gems & Jewellery", "Beauty & Personal Care", "Furniture & Home Furnishing", "Consumer Electronics",
  "Food Processing", "Dairy", "Agriculture & Agritech", "Fisheries & Aquaculture", "Renewable Energy", "Solar Energy",
  "Electric Vehicles", "Environmental Services", "Waste Management & Recycling", "Water & Utilities", "Shipping & Maritime",
  "Aviation & Airlines", "Railways", "Warehousing & Supply Chain", "Courier & Delivery Services", "Travel & Tourism",
  "Hotels & Resorts", "Restaurants & Food Services", "Events & Entertainment", "Gaming & Esports", "Sports & Fitness",
  "Film & Television", "Music & Audio", "Publishing", "News & Journalism", "Digital Media", "Social Media & Creator Economy",
  "Market Research", "Public Relations", "BPO & Call Centers", "BPO (Business Process Outsourcing)",
  "KPO & Knowledge Services", "KPO (Knowledge Process Outsourcing)", "Call Center & Contact Center Services",
  "International Call Center", "Travel Process & GDS Services", "Business Services",
  "Staffing & Recruitment", "Facilities Management", "Security Services", "NGOs & Nonprofits", "Social Services",
  "Research & Development", "Architecture & Design", "Interior Design", "Printing & Packaging", "Import & Export",
  "Wholesale & Distribution", "Franchise Businesses", "Professional Services", "Internet & Web Services", "Blockchain & Web3",
  "Space Technology",
]));
