"use client";
import { useEffect, useMemo, useState } from "react";
import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminHeader from "@/components/admin/AdminHeader";

type EventDef={eventKey:string;label:string;category:string;audiences:string[];channels:string[];variables:string[]};
type Template={id:string;eventKey:string;channel:string;audience:string;name:string;locale:string;status:string;provider?:string;providerAlias?:string;version:number;enabled:boolean};
type Delivery={id:string;eventKey:string;channel:string;status:string;provider?:string;attemptCount:number;createdAt:string};

export default function CommunicationsPage(){
 const [events,setEvents]=useState<EventDef[]>([]),[templates,setTemplates]=useState<Template[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const [deliveryStatus,setDeliveryStatus]=useState(""),[deliveryChannel,setDeliveryChannel]=useState("");
 const [eventKey,setEventKey]=useState(""),[channel,setChannel]=useState("WHATSAPP"),[audience,setAudience]=useState("CANDIDATE"),[name,setName]=useState(""),[alias,setAlias]=useState(""),[body,setBody]=useState(""),[subject,setSubject]=useState(""),[parameterOrder,setParameterOrder]=useState("");
 async function load(){setLoading(true);setError("");const q=new URLSearchParams({limit:"50"});if(deliveryStatus)q.set("status",deliveryStatus);if(deliveryChannel)q.set("channel",deliveryChannel);const [r,d]=await Promise.all([fetch("/api/admin/communications/templates",{cache:"no-store"}),fetch(`/api/admin/communications/deliveries?${q}`,{cache:"no-store"})]);const j=await r.json(),dj=await d.json();if(!r.ok||!d.ok){setError(j.error||dj.error||"Unable to load communications.");setLoading(false);return}setEvents(j.events||[]);setTemplates(j.templates||[]);setDeliveries(dj.deliveries||[]);if(!eventKey&&j.events?.[0])setEventKey(j.events[0].eventKey);setLoading(false)}
 useEffect(()=>{load()},[]);
 const def=useMemo(()=>events.find(e=>e.eventKey===eventKey),[events,eventKey]);
 useEffect(()=>{if(def&&!def.channels.includes(channel))setChannel(def.channels[0]||"EMAIL");if(def&&!def.audiences.includes(audience))setAudience(def.audiences[0]||"CANDIDATE")},[def,channel,audience]);
 async function toggle(t:Template){setError("");const r=await fetch(`/api/admin/communications/templates/${t.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!t.enabled})});const j=await r.json();if(!r.ok){setError(j.error||"Unable to update template.");return}await load()}
 async function create(){setError("");const mapping=parameterOrder.split(",").map(v=>v.trim()).filter(Boolean);if(channel==="WHATSAPP"){const invalid=mapping.filter(v=>!def?.variables.includes(v));const duplicate=mapping.filter((v,i)=>mapping.indexOf(v)!==i);if(invalid.length){setError(`Unknown Meta parameters: ${[...new Set(invalid)].join(", ")}`);return}if(duplicate.length){setError(`Duplicate Meta parameters: ${[...new Set(duplicate)].join(", ")}`);return}}const provider=channel==="WHATSAPP"?"META":"ZEPTOMAIL";const r=await fetch("/api/admin/communications/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventKey,channel,audience,name,locale:"en",provider,providerAlias:alias,subject:channel==="EMAIL"?subject||undefined:undefined,body,providerParameterOrder:channel==="WHATSAPP"?mapping:undefined,enabled:false})});const j=await r.json();if(!r.ok){setError(j.error||"Unable to create template.");return}setName("");setAlias("");setBody("");setSubject("");setParameterOrder("");await load()}
 return <div className="min-h-screen bg-[#0E0E0E] text-white flex"><AdminSidebar/><div className="flex-1 md:ml-[116px] min-w-0"><AdminHeader title="Communications"/><main className="p-4 sm:p-6 lg:p-8 pt-24 max-w-[1600px] mx-auto">
  {loading&&<div className="mb-4 text-sm text-zinc-500">Loading communication operations…</div>}
  <div className="mb-8"><h1 className="text-3xl font-semibold">Communication Center</h1><p className="text-zinc-400 mt-2">Manage HireGo transactional WhatsApp and email templates, lifecycle events and delivery operations.</p></div>
  {error&&<div className="mb-6 rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-200">{error}</div>}
  <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-8">{[["Events",events.length],["Templates",templates.length],["Active",templates.filter(t=>t.enabled).length],["Channels","WhatsApp + Email"]].map(([a,b])=><div key={String(a)} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="text-sm text-zinc-500">{a}</div><div className="text-2xl mt-2 font-semibold">{b}</div></div>)}</div>
  <div className="grid grid-cols-1 xl:grid-cols-5 gap-6">
   <section className="xl:col-span-3 rounded-2xl border border-zinc-800 bg-zinc-950 overflow-hidden"><div className="p-5 border-b border-zinc-800"><h2 className="font-semibold">Template catalogue</h2></div><div className="divide-y divide-zinc-900">{templates.length?templates.map(t=><div key={t.id} className="p-5 flex items-center justify-between"><div><div className="font-medium">{t.name}</div><div className="text-xs text-zinc-500 mt-1">{t.eventKey} · {t.audience} · v{t.version}</div></div><div className="flex gap-2"><span className="rounded-full bg-zinc-800 px-3 py-1 text-xs">{t.channel}</span><span className="rounded-full bg-zinc-800 px-3 py-1 text-xs">{t.status}</span><button onClick={()=>toggle(t)} className="rounded-full border border-zinc-700 px-3 py-1 text-xs hover:bg-zinc-800">{t.enabled?"Disable":"Activate"}</button></div></div>):<div className="p-10 text-center text-zinc-500">No templates yet. Create the first controlled template.</div>}</div></section>
   <section className="xl:col-span-2 rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold mb-5">Create template draft</h2><div className="space-y-4">
    <label className="block text-sm">Business event<select value={eventKey} onChange={e=>setEventKey(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3">{events.map(e=><option key={e.eventKey} value={e.eventKey}>{e.category} — {e.label}</option>)}</select></label>
    <div className="grid grid-cols-2 gap-3"><label className="text-sm">Channel<select value={channel} onChange={e=>setChannel(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3">{(def?.channels||["WHATSAPP","EMAIL"]).map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Audience<select value={audience} onChange={e=>setAudience(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3">{(def?.audiences||["CANDIDATE"]).map(a=><option key={a}>{a}</option>)}</select></label></div>
    <label className="block text-sm">Template name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3"/></label>
    <label className="block text-sm">Provider alias / Meta template name<input value={alias} onChange={e=>setAlias(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3"/></label>
    {channel==="EMAIL"&&<label className="block text-sm">Email subject<input value={subject} onChange={e=>setSubject(e.target.value)} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3"/></label>}
    {channel==="WHATSAPP"&&<label className="block text-sm">Meta body parameter order<input value={parameterOrder} onChange={e=>setParameterOrder(e.target.value)} placeholder="candidate_name, company_name, job_title" className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3"/><span className="mt-1 block text-xs text-zinc-500">Comma-separated variable names in the exact order configured in Meta.</span></label>}
    <label className="block text-sm">Preview body<textarea value={body} onChange={e=>setBody(e.target.value)} rows={7} className="mt-2 w-full rounded-xl bg-zinc-900 border border-zinc-700 p-3"/></label>
    <div className="text-xs text-zinc-500">Allowed variables: {(def?.variables||[]).map(v=>`{{${v}}}`).join(", ")||"None"}</div>
    <button onClick={create} disabled={!eventKey||!name||!body||(channel==="WHATSAPP"&&!parameterOrder.trim())} className="w-full rounded-xl bg-white text-black font-medium p-3 disabled:opacity-40">Save draft</button>
   </div></section>
  </div>
 <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 overflow-hidden"><div className="p-5 border-b border-zinc-800 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><h2 className="font-semibold">Recent delivery operations</h2><div className="flex flex-wrap gap-2"><select aria-label="Delivery status" value={deliveryStatus} onChange={e=>setDeliveryStatus(e.target.value)} className="rounded-lg bg-zinc-900 border border-zinc-700 px-3 py-2 text-sm"><option value="">All statuses</option>{["PENDING","PROCESSING","ACCEPTED","DELIVERED","READ","FAILED"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Delivery channel" value={deliveryChannel} onChange={e=>setDeliveryChannel(e.target.value)} className="rounded-lg bg-zinc-900 border border-zinc-700 px-3 py-2 text-sm"><option value="">All channels</option><option>EMAIL</option><option>WHATSAPP</option></select><button onClick={load} className="rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800">Apply filters</button></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-zinc-500"><tr><th className="p-4 text-left">Event</th><th>Channel</th><th>Status</th><th>Provider</th><th>Attempts</th><th>Created</th></tr></thead><tbody>{deliveries.length?deliveries.map(d=><tr key={d.id} className="border-t border-zinc-900"><td className="p-4">{d.eventKey}</td><td className="text-center">{d.channel}</td><td className="text-center">{d.status}</td><td className="text-center">{d.provider||"—"}</td><td className="text-center">{d.attemptCount}</td><td className="text-center text-zinc-500">{new Date(d.createdAt).toLocaleString()}</td></tr>):<tr><td colSpan={6} className="p-10 text-center text-zinc-500">No delivery operations yet.</td></tr>}</tbody></table></div></section>
 </main></div></div>
}