import type { Metadata } from "next";
import Link from "next/link";
import MarketingShell from "@/components/marketing/MarketingShell";
import { EditorialHero, FAQ, FinalCTA, JsonLd, SectionHeading, breadcrumbSchema, styles } from "@/components/marketing/Editorial";
import { marketingMetadata } from "@/lib/marketingMetadata";

export const metadata: Metadata = marketingMetadata({ path: "/about", title: "About HireGo AI | Autonomous AI Hiring Platform", description: "Learn why HireGo AI is building an autonomous agentic hiring platform that connects sourcing, screening, assessments, interviews and hiring operations in one workflow.", image: "/marketing/og/about.webp" });

const disconnected = [["Job portal", "Candidate discovery"], ["ATS", "Application tracking"], ["Assessment platform", "Role-related tests"], ["Scheduling product", "Calendar coordination"], ["Video platform", "Interviews"], ["Messaging tools", "Follow-ups"]];
const stages = ["Employer Requirement","Requirement Understanding","Candidate Sourcing","Screening","Assessment","Interview Scheduling","Interview Coordination","Feedback","Human Hiring Decision","Joining Workflow"];
const specialists = ["Requirement","Sourcing","Screening","Assessment","Scheduling","Interview","Follow-up","Hiring Operations"];
const trust = ["Role-based permissions","Tenant-aware data access","Human authorization for consequential actions","Workflow auditability","Secure media handling","Candidate privacy","Clear assessment rules","Controlled AI actions"];
const faqs = [
  {question:"What is HireGo AI?",answer:"HireGo AI is an autonomous agentic hiring platform designed to connect candidate sourcing, screening, assessments, interview scheduling, interview workflows and hiring operations within one recruitment workflow."},
  {question:"Is HireGo AI a job portal?",answer:"Candidate discovery is one part of HireGo, but the platform is intended to go beyond job posting by helping employers execute and coordinate the hiring process after a requirement is created."},
  {question:"Does HireGo replace recruiters?",answer:"HireGo is designed to reduce repetitive recruiting operations and coordination work. Recruiters and authorized hiring teams remain responsible for human judgment and consequential hiring decisions."},
  {question:"Who can use HireGo AI?",answer:"HireGo is designed for employers, recruiting teams and candidates. Employer workflows can support sourcing, assessments, interviews and hiring operations, while candidate experiences can include profiles, assessments, interview preparation and job opportunities."},
];

export default function AboutPage() {
  return <MarketingShell><div className={styles.page}>
    <EditorialHero eyebrow="About HireGo AI" current="About Us" title="We believe hiring should move like one workflow, not ten disconnected tools." lead="HireGo AI is building an autonomous hiring platform that helps employers execute recruitment workflows from job requirement to joining while keeping people in control of consequential hiring decisions." image="/marketing/about-hirego-agentic-hiring.webp" alt="Illustrative HireGo AI platform connecting an employer requirement to candidate progression with a human decision checkpoint" primary={{label:"Explore the Platform",href:"/features"}} secondary={{label:"See Our Services",href:"/services"}} />

    <section className={styles.section} id="why"><div className={styles.container}><SectionHeading eyebrow="Why we exist" title="Hiring has a workflow problem." body="Most hiring technology solves one piece of recruitment. Employers still connect those pieces manually." /><div className={styles.grid3}>{disconnected.map(([tool,purpose])=><article className={styles.card} key={tool}><h3>{tool}</h3><p>{purpose}</p></article>)}</div><p className="mt-9 max-w-3xl text-lg leading-8 text-slate-600">After a job is created, someone still needs to find candidates, review profiles, contact people, check availability, send assessments, schedule interviewers, remind participants, collect feedback, move candidates to the next round and follow up after a decision. Together, those hand-offs create a large amount of recruiting operations work.</p><p className="mt-5 text-xl font-bold text-blue-800">HireGo AI exists to reduce that operational fragmentation.</p></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="our-idea"><div className={styles.container}><SectionHeading eyebrow="Our idea" title="What if the hiring workflow could operate intelligently?" body="We are building HireGo around specialized AI agents that can help execute defined parts of hiring, keep shared context and surface the steps that need a person." /><ol className={styles.flow}>{stages.map(stage=><li className={styles.flowItem} key={stage}>{stage}</li>)}</ol><p className="mt-7 text-lg font-semibold text-blue-900">One connected workflow. Shared context. Fewer manual hand-offs.</p></div></section>

    <section className={styles.section} id="specialists"><div className={styles.container}><SectionHeading eyebrow="Specialized agents" title="Agentic hiring requires more than one generic AI assistant." body="Different parts of recruitment require different context, permissions and responsibilities. HireGo’s architecture is being built around specialist agents that cooperate across one workflow." /><div className={styles.agentGrid}>{specialists.map(title=><div className={styles.agent} key={title}><h3>{title}</h3><p>Works on its defined stage and passes context forward within permitted workflow rules.</p></div>)}</div><div className={styles.notice}><strong>Bounded by permissions.</strong>Each agent should pass context to the next stage, rather than operate as an unrestricted autonomous system.</div></div></section>

    <section className={`${styles.section} ${styles.sectionDark}`} id="human-control"><div className={styles.container}><SectionHeading eyebrow="Responsible automation" title="Automation should remove repetitive work, not accountability." body="Hiring decisions affect people’s careers and companies’ teams. HireGo’s direction is to make operational hiring more capable while preserving human judgment." /><blockquote className={styles.quote}>“AI can operate the workflow. People remain accountable for the decision.”</blockquote><p className={styles.body}>The platform can help collect evidence, organize candidates, coordinate assessments, schedule interviews and prepare the next action. Consequential hiring actions should remain governed by permissions, workflow rules and appropriate human authorization.</p><div className="mt-8 inline-flex rounded-2xl border border-cyan-300/40 bg-cyan-300/10 px-6 py-5 text-lg font-bold text-cyan-100">Agent workflow → Human approval → Final decision</div></div></section>

    <section className={styles.section} id="difference"><div className={styles.container}><SectionHeading eyebrow="Our focus" title="We are building beyond individual hiring tools." body="Each tool category has a useful purpose. HireGo’s focus is connecting the work between them." /><div className={styles.tableWrap}><table className={styles.comparison}><thead><tr><th scope="col">Approach</th><th scope="col">Primary purpose</th></tr></thead><tbody><tr><td>Traditional job portal</td><td>Candidate discovery</td></tr><tr><td>Traditional ATS</td><td>Application tracking</td></tr><tr><td>AI interview tool</td><td>Interview or assessment</td></tr><tr><td>Scheduling tool</td><td>Calendar coordination</td></tr><tr><td>HireGo AI</td><td>Connected hiring workflow orchestration from requirement through hiring operations</td></tr></tbody></table></div><p className="mt-6 max-w-3xl leading-7 text-slate-600">HireGo does not need to replace every tool overnight. The goal is to connect the workflow and reduce the manual work required to keep hiring moving.</p></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="who"><div className={styles.container}><SectionHeading eyebrow="The people we serve" title="Built for both sides of the hiring journey." /><div className={styles.grid3}><article className={styles.card}><h3>Employers</h3><p>Structure and operate hiring workflows with more automation, clearer evidence and fewer manual hand-offs.</p></article><article className={styles.card}><h3>Candidates</h3><p>Present evidence, complete structured assessments, practice interviews and move through a clearer hiring experience.</p></article><article className={styles.card}><h3>Recruiters</h3><p>Use an operational layer for repetitive workflow tasks while focusing on candidate quality, communication and decisions.</p></article></div></div></section>

    <section className={styles.section} id="models"><div className={styles.container}><SectionHeading eyebrow="Working with HireGo" title="Different companies need different ways to hire." body="Some companies want software. Some want automation. Some want the hiring workflow supported. HireGo is being built to accommodate those differences." /><div className={styles.grid3}><article className={styles.card}><h3>Subscription</h3><p>Recurring access to platform capabilities and available autonomous workflow features.</p></article><article className={styles.card}><h3>Managed Hiring — Pay Per Hire</h3><p>Outcome-oriented hiring support for employers that want HireGo to help operate recruitment.</p></article><article className={styles.card}><h3>Pay Per Interview</h3><p>Structured interview services for companies needing interview capacity without a full recurring workflow, where available.</p></article></div><Link className={styles.inlineLink} href="/services#commercial-models">Compare ways to work with HireGo ↗</Link></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="trust"><div className={styles.container}><SectionHeading eyebrow="Trust by design" title="Trust has to be part of the architecture." body="Recruitment systems handle sensitive candidate and employer information. HireGo is being designed with clear access boundaries, workflow authorization, auditability and controlled automation as product requirements." /><div className={styles.grid4}>{trust.map(item=><div className={styles.card} key={item}><h3>{item}</h3></div>)}</div><div className={styles.actions}><Link href="/privacy" className={styles.inlineLink}>Read our privacy information ↗</Link><Link href="/terms" className={styles.inlineLink}>Read our terms ↗</Link><Link href="/contact" className={styles.inlineLink}>Contact HireGo ↗</Link></div></div></section>

    <section className={styles.section} id="mission"><div className={`${styles.container} ${styles.split}`}><div><p className={styles.eyebrow}>Our mission</p><h2 className="mt-4">Make hiring execution dramatically simpler without removing the people responsible for the outcome.</h2><p className={styles.body}>We want employers to spend less time coordinating recruiting operations and more time understanding candidates. We want candidates to experience clearer processes, faster communication and more ways to demonstrate what they can do.</p></div><div className={styles.card}><p className={styles.eyebrow}>Our vision</p><h3 className="mt-4 text-2xl">Where we believe hiring is going</h3><p>The next generation of recruiting software will increasingly understand workflows, coordinate actions across systems and help complete operational work.</p><p>We believe hiring will move from isolated AI features toward connected agentic systems that collaborate with people throughout the process.</p><p><strong>That is the future HireGo AI is being built for.</strong></p><Link className={styles.inlineLink} href="/services">See how HireGo works ↗</Link></div></div></section>

    <FAQ title="Questions about HireGo AI" items={faqs} />
    <FinalCTA title="Explore a more connected hiring workflow." body="See what HireGo is building, who it serves and where human approval belongs." primary={{label:"Explore Services",href:"/services"}} secondary={{label:"Explore Solutions",href:"/solutions"}} />
    <JsonLd data={[breadcrumbSchema("About Us","/about"), {"@context":"https://schema.org","@type":"Organization",name:"HireGo AI",url:"https://hiregoai.com",logo:"https://hiregoai.com/marketing/hirego-logo-hd.png",description:"HireGo AI builds connected hiring workflow orchestration with human-controlled hiring decisions."}]} />
  </div></MarketingShell>;
}
