"use client";
import React, { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

type Attempt = { id:string; status:string; mediaType:string; createdAt:string; candidateProfile:{user:{name:string;email:string}}; proctoringEvents:Array<{id:string;eventType:string;severity:string;warningNumber:number|null;createdAt:string}>; questions:Array<{id:string;questionText:string;answerDurationSeconds:number;response:null|{id:string;durationSeconds:number;transcript:string|null;analysisStatus:string;analysisResult:unknown;storedFile:null|{id:string;mimeType:string}}}> };
export default function RecordedAssessmentReviewPage(){
 const q=useSearchParams(); const jobId=q.get("jobId")||""; const [items,setItems]=useState<Attempt[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{ if(!jobId){setError("Select a job to review recorded assessments.");setLoading(false);return;} fetch(`/api/employer/jobs/${jobId}/recorded-assessment/attempts`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load assessments.");return b;}).then(b=>setItems(b.attempts)).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[jobId]);
 return <div className="max-w-6xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold">Recorded Assessment Review</h1><p className="text-sm text-text-secondary mt-1">Review candidate answers, transcripts, analysis status and observable proctoring events. Proctoring signals are evidence for human review, not an automatic hiring decision.</p></div>
 {loading&&<div className="rounded-2xl border border-outline bg-bg-card p-6">Loading assessments…</div>}{error&&<div role="alert" className="rounded-2xl border border-outline bg-bg-card p-6">{error}</div>}
 {!loading&&!error&&items.length===0&&<div className="rounded-2xl border border-outline bg-bg-card p-6">No recorded assessment attempts for this job yet.</div>}
 <div className="space-y-5">{items.map(a=><article key={a.id} className="rounded-3xl border border-outline bg-bg-card p-5 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{a.candidateProfile.user.name}</h2><p className="text-xs text-text-secondary">{a.candidateProfile.user.email}</p></div><div className="text-xs text-text-secondary">{a.status} · {a.mediaType} · {a.proctoringEvents.length} proctoring events</div></div>
 <div className="space-y-4">{a.questions.map((x,i)=><div key={x.id} className="rounded-2xl bg-bg-elevated p-4 space-y-3"><p className="text-xs font-bold">Question {i+1}</p><p className="text-sm">{x.questionText}</p>{x.response?<><div className="flex flex-wrap gap-3 text-xs text-text-secondary"><span>{x.response.durationSeconds}s recorded</span><span>Analysis: {x.response.analysisStatus}</span></div>{x.response.storedFile&&<video controls preload="metadata" className="w-full max-w-xl rounded-xl" src={`/api/files/${x.response.storedFile.id}`} />}{x.response.transcript&&<div><p className="text-xs font-bold mb-1">Transcript</p><p className="text-sm text-text-secondary whitespace-pre-wrap">{x.response.transcript}</p></div>}</>:<p className="text-xs text-text-secondary">No response saved.</p>}</div>)}</div>
 {a.proctoringEvents.length>0&&<details className="rounded-2xl border border-outline p-4"><summary className="cursor-pointer font-bold text-sm">Proctoring evidence</summary><div className="mt-3 space-y-2">{a.proctoringEvents.map(e=><div key={e.id} className="text-xs text-text-secondary">{e.eventType} · {e.severity}{e.warningNumber?` · warning ${e.warningNumber}/3`:""} · {new Date(e.createdAt).toLocaleString()}</div>)}</div></details>}
 </article>)}</div></div>;
}
