import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { createMarketingMetadata } from "@/lib/marketingMetadata";

export const metadata: Metadata = createMarketingMetadata("home");
import MarketingShell from "@/components/marketing/MarketingShell";

export default function HomePage() {
  return (
    <MarketingShell>
      <section className="relative flex min-h-[90vh] flex-col justify-center overflow-hidden px-5 py-28 sm:px-8">
        <div className="absolute inset-0 z-0 overflow-hidden bg-[#020617]">
          <Image src="/marketing/images/interactive_world_map_globe.png" alt="" fill sizes="100vw" className="object-cover object-center opacity-65" priority />
          <div className="absolute inset-0 bg-gradient-to-t from-[#050510] via-transparent to-[#050510]/80" />
          <div className="absolute inset-0 bg-gradient-to-r from-[#050510]/80 via-transparent to-[#050510]/80" />
        </div>
        <div className="relative z-10 mx-auto max-w-5xl text-center">
          <p className="mb-5 text-sm font-bold uppercase tracking-[0.22em] text-cyan-300">Autonomous hiring, made human</p>
          <h1 className="text-5xl font-black leading-[1.08] tracking-tight text-white drop-shadow-2xl sm:text-7xl">World&apos;s <span className="bg-gradient-to-r from-cyan-400 via-violet-400 to-fuchsia-400 bg-clip-text text-transparent">Fastest Hiring</span><br />Platform.</h1>
          <p className="mx-auto mt-7 max-w-3xl text-lg font-medium leading-8 text-slate-200 drop-shadow-md sm:text-xl">Reducing recruitment time by up to <span className="font-bold text-cyan-300">90%</span>. Screen, assess, and interview candidates automatically with intelligent agents across the globe.</p>
          <div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row">
            <Link href="/register?type=employer" className="btn-primary-blue min-w-[220px] px-7">Get started free <span aria-hidden>→</span></Link>
            <Link href="/contact" className="btn-ghost min-w-[220px] border-white/30 bg-white/5 px-7 text-white hover:bg-white/10">Talk to our team <span aria-hidden>→</span></Link>
          </div>
        </div>
      </section>
      <section className="relative overflow-hidden bg-gradient-to-br from-slate-50 via-white to-blue-50 px-5 py-16 sm:px-8 md:py-24">
        <div className="pointer-events-none absolute inset-0 opacity-50" style={{ backgroundImage: "radial-gradient(#dbe4f0 1px, transparent 1px)", backgroundSize: "16px 16px" }} />
        <div className="relative mx-auto max-w-7xl text-center">
          <h2 className="bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-4xl">Trusted by industry leaders</h2>
          <p className="mx-auto mt-3 max-w-xl text-slate-600">Top companies use HireGo AI to find and hire exceptional talent faster than ever.</p>
          <div className="mt-10 grid grid-cols-2 gap-3 rounded-[2rem] border-4 border-white bg-white p-5 shadow-[0_20px_60px_-15px_rgba(0,0,0,0.2)] sm:grid-cols-3 lg:grid-cols-6">
            {['Google','TCS','Microsoft','Infosys','Amazon','Zomato','Slack','Wipro','Stripe','Cognizant','Swiggy','Spotify'].map((company) => <div key={company} className="flex h-12 items-center justify-center rounded-xl bg-slate-50 px-3 text-sm font-bold text-slate-500">{company}</div>)}
          </div>
          <div className="mt-14 grid grid-cols-2 gap-8 md:grid-cols-4">
            {[['500+','Partner Companies'],['50K+','Successful Hires'],['12','Countries'],['99%','Satisfaction Rate']].map(([value,label]) => <div key={label}><div className="text-3xl font-extrabold text-slate-900 sm:text-4xl">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>)}
          </div>
        </div>
      </section>
      <section className="bg-white px-5 py-16 sm:px-8 md:py-24">
        <div className="mx-auto max-w-7xl">
          <div className="text-center"><h2 className="text-3xl font-extrabold text-slate-900 sm:text-4xl">Trusted Results Worldwide</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">A hiring engine built for speed, quality, and scale.</p></div>
          <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {[['10 min','Avg. Hiring Time','Reducing industry timelines by 45 days on average'],['85%','Time Saving','Faster than traditional hiring'],['50K+','Successful Hirings','Across 12 countries'],['99.9%','Accuracy Rate','Verified AI matching']].map(([value,label,description]) => <article key={label} className="rounded-3xl border border-slate-200 bg-gradient-to-br from-white to-blue-50 p-6 text-center shadow-sm"><div className="text-3xl font-black text-slate-900">{value}</div><h3 className="mt-2 font-bold text-slate-800">{label}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}
          </div>
        </div>
      </section>
      <section className="bg-gradient-to-br from-slate-50 via-white to-purple-50 px-5 py-16 sm:px-8 md:py-24">
        <div className="mx-auto max-w-7xl"><div className="text-center"><h2 className="text-3xl font-extrabold text-slate-900 sm:text-4xl">Built for worldwide hiring.</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">Premium features designed for modern engineering teams and global enterprises.</p></div>
          <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[['Autonomous AI Agents','10-MINUTE AVERAGE TIME-TO-SHORTLIST','AI agents work 24/7 to automate screening, evaluation, and candidate ranking, cutting manual work to almost zero.','from-blue-500 to-cyan-400'],['Lightning Fast Hiring','REDUCE RECRUITER WORKLOAD BY UP TO 80%','Go from job posting to qualified shortlist in minutes, not weeks, so you fill urgent roles before competitors even start.','from-purple-600 to-fuchsia-500'],['Precision Matching','95% CANDIDATE-JOB FIT ACCURACY','AI-powered matching based on skills, experience, culture fit, and growth potential for highly accurate placements.','from-emerald-500 to-teal-400'],['AI Video Interviews','SCREEN 100+ CANDIDATES SIMULTANEOUSLY','Automated video interviews with behavioral analysis, sentiment detection, and clear, actionable candidate reports.','from-rose-500 to-orange-400'],['AI Anti-Cheating Engine','99.9% FRAUD DETECTION RATE','Advanced proctoring ensures fair, authentic assessments with real-time fraud detection and identity verification.','from-indigo-600 to-blue-500'],['Global Talent Access','ACCESS 50+ COUNTRIES INSTANTLY','Connect with verified talent worldwide. No borders, no limits, reduced visa headaches for global hiring teams.','from-cyan-500 to-green-400']].map(([title,outcome,description,gradient]) => <article key={title} className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`mb-6 h-2 w-20 rounded-full bg-gradient-to-r ${gradient}`} /><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 text-xs font-bold uppercase tracking-wider text-blue-600">{outcome}</p><p className="mt-3 leading-7 text-slate-600">{description}</p></article>)}</div>
        </div>
      </section>
      <section className="bg-[#050510] px-5 py-16 sm:px-8 md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">Autonomous AI agents</p><h2 className="mt-4 text-3xl font-extrabold text-white sm:text-5xl">Agentic Hiring Dashboard</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-300">Our AI agents go beyond resumes, delivering behavioral insights, skill verification, and culture-fit analysis in a single, intuitive dashboard.</p><div className="mt-8 flex gap-8"><div><div className="text-3xl font-black text-cyan-300">98.5%</div><div className="mt-1 text-sm text-slate-400">Matching Accuracy</div></div><div><div className="text-3xl font-black text-violet-300">10 min</div><div className="mt-1 text-sm text-slate-400">Time to Shortlist</div></div></div><Link href="/ai-features" className="btn-primary-blue mt-8">Explore AI features →</Link></div><div className="overflow-hidden rounded-3xl border border-white/15 bg-white/5 p-2 shadow-2xl shadow-cyan-500/10"><Image src="/marketing/images/ai_hiring_dashboard_real.png" alt="HireGo AI management dashboard" width={1200} height={800} className="h-auto w-full rounded-2xl" /></div></div></section>
      <section className="bg-white px-5 py-16 sm:px-8 md:py-24"><div className="mx-auto max-w-7xl"><div className="text-center"><h2 className="text-3xl font-extrabold text-slate-900 sm:text-4xl">Your entire hiring pipeline, fully automated.</h2><p className="mt-3 text-slate-600">From job posting to offer letter in record time.</p></div><div className="mt-12 grid gap-5 md:grid-cols-4">{[['1','Post Job','Create your job in seconds with AI-assisted requirements.','Import your JD or let AI generate one in under 30 seconds'],['2','AI Screens','AI agents instantly screen and rank every applicant.','Evaluate 1000+ candidates in under 5 minutes with zero manual effort'],['3','Auto Interview','Candidates complete AI-powered, fraud-proof video interviews.','Behavioral insights, skill verification, and cheating detection in one report'],['4','Hire Fast','Get a ranked shortlist with rich, actionable profiles.','Review, compare, and send offers in minutes, not weeks']].map(([number,title,description,microcopy]) => <article key={number} className="rounded-[2rem] bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 text-xl font-black text-white">{number}</div><h3 className="mt-6 text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 text-slate-700">{description}</p><p className="mt-5 text-xs font-bold uppercase tracking-wide text-slate-500">{microcopy}</p></article>)}</div></div></section>
      <section className="bg-gradient-to-br from-slate-50 via-white to-blue-50 px-5 py-16 sm:px-8 md:py-24"><div className="mx-auto max-w-7xl text-center"><h2 className="text-3xl font-extrabold text-slate-900 sm:text-4xl">Trusted by leaders.</h2><p className="mt-3 text-slate-600">See why the world&apos;s best companies hire with HireGo.</p><div className="mt-10 grid gap-5 text-left md:grid-cols-2 lg:grid-cols-4">{[['P','Priya Sharma','HR Director, TCS','HireGo AI agents slashed our time-to-hire by 70%. We closed 15 senior dev roles in a week.'],['J','James Wilson','CTO, Microsoft','The technical assessments vary dynamically. It&apos;s impossible to cheat, and the candidates are top-tier.'],['A','Anita Desai','Talent Lead, Infosys','Finally, an AI tool that actually understands culture fit. The candidate summaries are scary accurate.'],['R','Rahul Verma','Founder, Razorpay','As a small team, we could not afford a recruiter. HireGo acted as our entire HR department.']].map(([initial,name,role,quote]) => <article key={name} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 font-bold text-white">{initial}</div><p className="mt-5 leading-7 text-slate-700">&quot;{quote}&quot;</p><p className="mt-5 font-bold text-slate-900">{name}</p><p className="text-sm text-slate-500">{role}</p></article>)}</div></div></section>
      <section className="bg-[#050510] px-5 py-20 text-center sm:px-8 md:py-28"><h2 className="text-3xl font-extrabold text-white sm:text-5xl">Ready to scale, without scaling your HR team?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Join companies worldwide using HireGo AI to run autonomous, 24/7 hiring. Start free today.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="btn-primary-blue px-7">Get started free</Link><Link href="/contact" className="btn-ghost border-white/30 bg-white/5 px-7 text-white hover:bg-white/10">Contact sales</Link></div></section>
    </MarketingShell>
  );
}
