import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import MarketingShell from "@/components/marketing/MarketingShell";
import ManagedHiringVisual from "@/components/marketing/ManagedHiringVisual";
import { EditorialHero, FAQ, FinalCTA, JsonLd, SectionHeading, breadcrumbSchema, styles } from "@/components/marketing/Editorial";
import { marketingMetadata } from "@/lib/marketingMetadata";

export const metadata: Metadata = marketingMetadata({
  path: "/services",
  title: "Managed Hiring & Pay Per Hire Services | HireGo AI",
  description: "HireGo helps employers source and coordinate candidates through Managed Hiring. Your team makes the final decision; Pay Per Hire fees follow agreed successful hire terms.",
  image: "/marketing/og/services.webp",
});

const agents = [
  ["Understand the role", "We agree on the skills, experience, interview stages and evidence that matter for this hire."],
  ["Find and engage", "Our team uses approved sources and useful tools to identify and contact relevant candidates."],
  ["Keep interviews moving", "Scheduling, reminders and feedback stay organized so candidates and hiring teams know what comes next."],
  ["Support the decision", "We bring the context together. Your hiring team evaluates people and makes the final choice."],
];
const backendSteps = ["Job requirement created", "Relevant candidates sourced", "Candidates organized against the requirement", "Qualified candidates invited", "Assessment coordinated when required", "Interview availability collected", "Interview scheduled", "Interviewers receive context", "Feedback collected", "Hiring team makes the decision", "Selected candidate enters joining workflow"];
const assessmentItems = [
  ["MCQ Assessments", "Evaluate role-related knowledge with structured questions and server-side scoring."],
  ["Recorded Audio & Video Responses", "Ask candidates to respond to short role-related questions using controlled response windows."],
  ["Interview Readiness Evidence", "Give hiring teams additional context before committing interviewer time."],
  ["Proctoring Controls", "Where enabled, assessment workflows can include integrity checks and proctoring events designed to identify suspicious behavior."],
];
const commercial = [
  { title: "Managed Hiring — Pay Per Hire", best: "For employers that want HireGo to help operate hiring instead of running every step internally.", body: "HireGo coordinates the agreed workflow using its platform, automation and hiring operations capabilities. Fees are tied to a successful hiring outcome under agreed terms.", detail: "The employer retains the final hiring decision.", label: "Talk to Managed Hiring", href: "/contact" },
  { title: "Subscription", best: "For teams that hire continuously and want HireGo in their recruiting infrastructure.", body: "Use HireGo’s platform, workflows and available automation under a recurring plan based on the capabilities and usage included in your subscription.", detail: "Job workflows, sourcing, screening, assessments, scheduling, Co-Pilot allowances and team access depend on the plan.", label: "View Pricing", href: "/pricing" },
  { title: "Pay Per Interview", best: "For companies that need structured interview capacity without a full recurring workflow.", body: "Where available, use HireGo for individual interview requirements or interview-volume packages based on the required format and duration.", detail: "Availability and commercial terms are discussed with the team.", label: "Discuss Interview Requirements", href: "/contact" },
];
const faqs = [
  { question: "What is autonomous hiring?", answer: "Autonomous hiring uses software agents to execute permitted recruitment operations such as sourcing, assessment routing, scheduling and follow-ups. In HireGo, workflow execution is designed to work alongside human hiring decisions rather than replace employer accountability." },
  { question: "What does Employer Co-Pilot do?", answer: "Employer Co-Pilot helps coordinate a workflow after a role is created. Depending on configuration and permissions, it can assist with sourcing, candidate workflow movement, assessments, scheduling, reminders and other operational tasks." },
  { question: "Does HireGo AI automatically reject candidates?", answer: "Consequential hiring decisions can remain under the control of authorized hiring teams. AI helps organize evidence, automate workflow tasks and surface candidates for review without replacing employer responsibility for final decisions." },
  { question: "What is Managed Hiring Pay Per Hire?", answer: "Managed Hiring is for employers that want HireGo to help operate the hiring workflow. Under Pay Per Hire, fees are connected to a successful hiring outcome according to agreed terms rather than only software access." },
  { question: "Can companies use HireGo without Managed Hiring?", answer: "Yes. Employers can use available subscription plans and operate their hiring workflows internally." },
];

export default function ServicesPage() {
  return <MarketingShell><div className={styles.page}>
    <EditorialHero eyebrow="Managed Hiring · Pay Per Hire" current="Services" title="Tell us who you need. We help you hire." lead="HireGo combines a hiring team, a connected workflow and useful tools to help source candidates, coordinate interviews and keep the process moving. You meet the people, review the evidence and make the final decision." note="Our main service is Managed Hiring. The Pay Per Hire fee is tied to a successful hire under the terms agreed with your company." visual={<ManagedHiringVisual />} primary={{label:"Discuss Managed Hiring",href:"/contact"}} secondary={{label:"See how it works",href:"#managed-hiring"}} />

    <section className={styles.section} id="managed-hiring"><div className={styles.container}><SectionHeading eyebrow="Our core service" title="Managed Hiring, from requirement to joining." body="Share the role and what matters to your team. HireGo helps run the agreed sourcing, screening and coordination work. Your team meets candidates and decides whom to hire. Our success fee follows the successful hire event defined in your agreement." /><ol className={styles.flow}>{["Define the role together","Find and engage candidates","Review relevant evidence","Coordinate interviews","Employer makes the decision","Support joining follow-up"].map(item=><li className={styles.flowItem} key={item}>{item}</li>)}</ol><div className={styles.notice}><strong>Pay Per Hire, with clear terms.</strong>The fee amount, trigger and any replacement or invoice terms are agreed with each employer before the engagement starts. <Link className={styles.inlineLink} href="/contact">Talk to HireGo about your role ↗</Link></div></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="agents"><div className={styles.container}>
      <SectionHeading eyebrow="How the work moves" title="One hiring process, clear handoffs." body="HireGo people and tools work together across the stages that usually slow a hire down. Automation helps with permitted repetitive work, while recruiters and employers handle judgment and decisions." />
      <div className={styles.agentGrid}>{agents.map(([title,body])=><article className={styles.agent} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div>
      <div className={styles.notice}><strong>People stay responsible.</strong>Automation can support sourcing, assessment routing, scheduling and follow-up within defined permissions. Final candidate selection and rejection remain subject to the employer’s process and human authorization.</div>
    </div></section>

    <section className={styles.section} id="employer-copilot"><div className={`${styles.container} ${styles.split}`}>
      <div className={styles.prose}><p className={styles.eyebrow}>Hiring operations</p><h2>Employer Co-Pilot</h2><p><strong>An AI operations layer for your recruiting team.</strong></p><p>Employer Co-Pilot helps keep hiring moving after a job is created. Instead of manually checking every stage, sending every reminder and coordinating every next step, your team can define permitted actions and review the moments where human attention is needed.</p><ul className={styles.list}><li>Reduce coordination between tools, calendars, messages and stages.</li><li>Coordinate permitted invitations, assessments, scheduling and reminders.</li><li>Carry context forward through the workflow.</li><li>Reserve consequential hiring decisions for authorized people.</li></ul><Link className={styles.inlineLink} href="/features">Explore the HireGo platform ↗</Link></div>
      <figure className={styles.visual}><Image src="/marketing/employer-copilot-workflow.webp" alt="Illustrative Employer Co-Pilot interface with active job, candidate stages and a human approval checkpoint" width={1200} height={900} sizes="(max-width: 900px) 100vw, 46vw" /><figcaption className="px-3 pt-3 text-xs text-slate-600">Illustrative workflow visual. Available actions depend on product configuration.</figcaption></figure>
    </div><div className={`${styles.container} mt-14`}><h3 className="mb-5 text-xl font-bold">Example: Hiring a Backend Engineer</h3><p className="mb-6 max-w-3xl leading-7 text-slate-600">An employer defines skills, screening criteria, assessment needs, interview rounds and interviewer availability. Co-Pilot helps move the operational steps forward; the hiring team decides.</p><ol className={styles.flow}>{backendSteps.map(step=><li className={styles.flowItem} key={step}>{step}</li>)}</ol></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="candidate-sourcing"><div className={`${styles.container} ${styles.split}`}><div><SectionHeading eyebrow="Discover" title="Autonomous Candidate Sourcing" body="Candidate discovery should not end with publishing a job and waiting. HireGo AI can help employers identify relevant people from approved talent sources and existing candidate pools, then organize appropriate profiles in a structured sourcing workflow." /><Link className={styles.button} href="/solutions">Explore Hiring Solutions <span aria-hidden="true">↗</span></Link></div><div className={styles.card}><h3>Where sourcing helps</h3><div className={`${styles.grid2} mt-6`}>{["Urgent hiring","Hard-to-fill roles","Passive talent discovery","Existing pool re-engagement","High-volume sourcing","Repeat roles"].map(item=><p key={item} className="rounded-2xl bg-blue-50 p-4 font-semibold text-slate-700">{item}</p>)}</div></div></div></section>

    <section className={styles.section} id="screening"><div className={`${styles.container} ${styles.split}`}><div className={styles.prose}><p className={styles.eyebrow}>Review with context</p><h2>Structured Screening and Shortlisting</h2><p>HireGo helps organize candidate evidence around the role instead of forcing recruiters to compare every resume manually. Screening can combine employer-defined requirements with available skills, experience and assessment evidence.</p><p><strong>AI helps prioritize and organize evidence for human review.</strong></p></div><div className={styles.card}><h3>Candidate comparison</h3><p className="mb-5">A structured view can bring the relevant signals together:</p><ul className={styles.list}>{["Skill alignment","Relevant experience","Assessment status","Availability","Interview stage"].map(item=><li key={item}>{item}</li>)}</ul><p className="mt-6 rounded-xl bg-cyan-50 p-4 text-sm font-semibold text-blue-900">Human review required before a consequential decision</p></div></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="assessments"><div className={styles.container}><SectionHeading eyebrow="More than a resume" title="Role-Aligned Candidate Assessments" body="When a resume is not enough, employers can add structured evidence to the hiring workflow. HireGo supports assessment experiences designed around the role and hiring stage." /><div className={styles.grid4}>{assessmentItems.map(([title,body])=><article className={styles.card} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>

    <section className={styles.section} id="interview-orchestration"><div className={styles.container}><SectionHeading eyebrow="Interview operations" title="Interview Scheduling and Multi-Round Orchestration" body="Several people, rounds and calendars make interviews operationally expensive. HireGo helps coordinate availability, assignments, reminders, rescheduling, virtual rooms and structured feedback while each round keeps its context." /><ol className={styles.flow}>{["Candidate","HR Round","Technical Round","Operations Round","Final Round","Human Decision"].map(item=><li className={styles.flowItem} key={item}>{item}</li>)}</ol><div className={`${styles.grid3} mt-7`}>{["Interviewer assignment and availability","Round progression and scheduling","Feedback collection and completion state"].map(item=><div className={styles.card} key={item}><h3>{item}</h3></div>)}</div></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="mock-interview"><div className={`${styles.container} ${styles.split}`}><div className={styles.prose}><p className={styles.eyebrow}>Candidate readiness</p><h2>AI Mock Interviews for Candidate Readiness</h2><p><strong>Practice before the interview that matters.</strong></p><p>Mock Interview gives candidates a structured environment to practice role-related questions before a real employer interview. They can practice under realistic timing, improve answer structure, build familiarity and identify preparation gaps.</p><p>For example, a sales candidate can practice introductions, objection handling and customer scenarios, then review preparation feedback. It is a practice experience, not a psychological evaluation or hiring decision.</p><Link href="/contact" className={styles.inlineLink}>Ask about candidate interview preparation ↗</Link></div><figure className={styles.visual}><Image src="/marketing/hirego-ai-mock-interview.webp" alt="Illustrative HireGo mock interview interface showing a role-related question, preparation timer, answer timer and progress" width={1200} height={900} sizes="(max-width: 900px) 100vw, 46vw" /><figcaption className="px-3 pt-3 text-xs text-slate-600">Illustrative interface, not a product screenshot.</figcaption></figure></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="video-resume"><div className={`${styles.container} ${styles.split}`}><div><SectionHeading eyebrow="See more than a PDF" title="Let candidates explain their work in their own words." body="A short video resume can show how a candidate describes experience, a project and role knowledge. Where available, a transcript and presentation report help your team review faster. A person still decides what the evidence means for the job." /><Link className={styles.button} href="/video-resume">Explore video resumes ↗</Link></div><div className={styles.card}><p className={styles.eyebrow}>Candidate → HireGo → Employer</p><h3 className="mt-4">A human introduction, with useful context.</h3><ol className={`${styles.flow} mt-6`}>{["Candidate shares a short video","Report organizes key moments","Employer reviews the full application","Employer decides"].map(item=><li className={styles.flowItem} key={item}>{item}</li>)}</ol><p>Video is optional and should never be treated as an automatic rejection score.</p></div></div></section>

    <section className={`${styles.section} ${styles.tint}`} id="commercial-models"><div className={styles.container}><SectionHeading eyebrow="Ways to work together" title="Choose how you want to hire." body="Some teams want software, some want operational support, and some need interview capacity. Commercial scope and availability are agreed before work begins." /><div className={styles.grid3}>{commercial.map(item=><article className={styles.card} key={item.title}><h3>{item.title}</h3><p><strong>{item.best}</strong></p><p>{item.body}</p><p>{item.detail}</p><Link className={styles.inlineLink} href={item.href}>{item.label} ↗</Link></article>)}</div><p className="mt-7 max-w-3xl leading-7 text-slate-600"><strong>Need a hybrid model?</strong> HireGo can support a combination of recurring platform access, managed hiring or additional interview services where commercially available.</p></div></section>

    <FAQ items={faqs} />
    <FinalCTA title="A connected workflow starts with a clear requirement." body="Tell us how your team hires today. We can discuss the platform, operational services and the human approvals your process needs." primary={{label:"Start Hiring with HireGo",href:"/register?type=employer"}} secondary={{label:"Talk to Our Team",href:"/contact"}} />
    <JsonLd data={[breadcrumbSchema("Services","/services"), {"@context":"https://schema.org","@type":"Service",name:"HireGo AI hiring workflow services",description:"Candidate sourcing, structured screening, assessments, interview coordination and managed hiring with human-controlled hiring decisions.",provider:{"@type":"Organization",name:"HireGo AI",url:"https://hiregoai.com"},url:"https://hiregoai.com/services"}]} />
  </div></MarketingShell>;
}
