"use client";
import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useEmployer } from "@/context/EmployerContext";

type Config={mediaType:"AUDIO"|"VIDEO";defaultAnswerSeconds:30|60;questionCount:number;proctoringEnabled:boolean;isActive:boolean};
const defaults:Config={mediaType:"VIDEO",defaultAnswerSeconds:30,questionCount:6,proctoringEnabled:true,isActive:true};
export default function RecordedAssessmentConfigurationPage(){
 const {jobs,isLoading}=useEmployer(); const [jobId,setJobId]=useState(""); const [config,setConfig]=useState<Config>(defaults); const [available,setAvailable]=useState<number|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const job=useMemo(()=>jobs.find((x:any)=>x.id===jobId),[jobs,jobId]);
 useEffect(()=>{if(!jobId)return;setMessage("");Promise.all([
  fetch(`/api/employer/jobs/${jobId}/recorded-assessment`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Failed to load configuration.");return b;}),
  job?.title?fetch(`/api/admin/recorded-assessment/questions?roleTitle=${encodeURIComponent(job.title)}`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Failed to check question bank.");return b;}):Promise.resolve({questions:[]})
 ]).then(([a,b])=>{setConfig(a.config?{mediaType:a.config.mediaType,defaultAnswerSeconds:a.config.defaultAnswerSeconds,questionCount:a.config.questionCount,proctoringEnabled:a.config.proctoringEnabled,isActive:a.config.isActive}:defaults);setAvailable(b.questions?.length||0);}).catch(e=>setMessage(e.message));},[jobId,job?.title]);
 const save=async()=>{if(!jobId)return;setSaving(true);setMessage("");try{if(available!==null&&available<config.questionCount)throw new Error(`Only ${available} active role-matched questions are available. Add at least ${config.questionCount-available} more before activation.`);const r=await fetch(`/api/employer/jobs/${jobId}/recorded-assessment`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to save.");setMessage("Recorded assessment configuration saved.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.");}finally{setSaving(false);}};
 return <div className="max-w-5xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold">Recorded Assessment</h1><p className="text-sm text-text-secondary mt-1">Configure the automatic Audio/Video screening attached to a real job.</p></div>
 <div className="rounded-3xl border border-outline bg-bg-card p-6 space-y-5"><label className="block text-sm font-bold">Job<select value={jobId} onChange={e=>setJobId(e.target.value)} disabled={isLoading} className="mt-2 w-full min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"><option value="">Select a job</option>{jobs.map((j:any)=><option key={j.id} value={j.id}>{j.title} · {j.status}</option>)}</select></label>
 {jobId&&<><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm font-bold">Answer format<select value={config.mediaType} onChange={e=>setConfig({...config,mediaType:e.target.value as "AUDIO"|"VIDEO"})} className="mt-2 w-full min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"><option value="VIDEO">Video</option><option value="AUDIO">Audio + camera proctoring</option></select></label><label className="text-sm font-bold">Default answer window<select value={config.defaultAnswerSeconds} onChange={e=>setConfig({...config,defaultAnswerSeconds:Number(e.target.value) as 30|60})} className="mt-2 w-full min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"><option value={30}>30 seconds</option><option value={60}>60 seconds</option></select></label></div>
 <label className="block text-sm font-bold">Questions<input type="number" min={1} max={20} value={config.questionCount} onChange={e=>setConfig({...config,questionCount:Math.max(1,Math.min(20,Number(e.target.value)||1))})} className="mt-2 w-full min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/></label>
 <div className="rounded-2xl bg-bg-elevated p-4 text-sm"><p className="font-bold">Question-bank readiness</p><p className="text-text-secondary mt-1">{available===null?"Checking…":`${available} active questions currently match “${job?.title}”. ${config.questionCount} will be frozen when a candidate attempt is created.`}</p></div>
 <label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={config.proctoringEnabled} onChange={e=>setConfig({...config,proctoringEnabled:e.target.checked})}/><span className="text-sm font-bold">Continuous proctoring</span></label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={config.isActive} onChange={e=>setConfig({...config,isActive:e.target.checked})}/><span className="text-sm font-bold">Assessment active for candidates</span></label>
 <div className="rounded-2xl border border-outline p-4 text-sm text-text-secondary">Candidate flow is fixed: 10 seconds Read & Prepare → 3-2-1 → automatic 30/60-second answer recording → secure upload → next question. Existing attempts keep their frozen questions if the bank changes later.</div>
 <div className="flex flex-wrap gap-3"><button onClick={save} disabled={saving||available===null} className="min-h-11 rounded-full btn-3d-red px-6 font-bold disabled:opacity-50">{saving?"Saving…":"Save configuration"}</button><Link href={`/employer/assessments/recorded?jobId=${jobId}`} className="min-h-11 inline-flex items-center rounded-full border border-outline px-6 font-bold">Review attempts</Link></div></>}
 {message&&<p role="status" className="text-sm">{message}</p>}</div></div>;
}
