import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { ApiError, enforceRateLimit, getCurrentSession, handleApiError, readValidatedJson } from "@/lib";
import { getSessionCompany } from "@/lib/routeAuthorization";
import { logAuditEvent } from "@/lib/auditLogger";
const createSchema=z.object({name:z.string().trim().min(1).max(80)}).strict();
const updateSchema=z.object({collectionId:z.string().uuid(),candidateIds:z.array(z.string().uuid()).max(500)}).strict();
async function ctx(req:NextRequest){await enforceRateLimit(req,"employer_candidate_collections",60,60_000);const s=await getCurrentSession(req.headers);if(!s||!["EMPLOYER","RECRUITER"].includes(s.role))throw new ApiError("Employer access required.",403);const company=await getSessionCompany(s);return{s,company};}
export async function GET(req:NextRequest){try{const{company}=await ctx(req);const collections=await prisma.employerCandidateCollection.findMany({where:{companyId:company.id},select:{id:true,name:true,candidateIds:true},orderBy:{createdAt:"asc"}});return NextResponse.json({success:true,collections});}catch(e){return handleApiError(e);}}
export async function POST(req:NextRequest){try{const{s,company}=await ctx(req);const{name}=await readValidatedJson(req,createSchema,4*1024);const collection=await prisma.employerCandidateCollection.create({data:{companyId:company.id,createdById:s.id,name,candidateIds:[]},select:{id:true,name:true,candidateIds:true}});await logAuditEvent({userId:s.id,companyId:company.id,action:"CANDIDATE_COLLECTION_CREATED",resource:`CandidateCollection:${collection.id}`,details:`Collection ${name} created`,ipAddress:req.headers.get("x-forwarded-for")||undefined});return NextResponse.json({success:true,collection},{status:201});}catch(e){return handleApiError(e);}}
export async function PATCH(req:NextRequest){try{const{s,company}=await ctx(req);const{collectionId,candidateIds}=await readValidatedJson(req,updateSchema,64*1024);const valid=await prisma.application.findMany({where:{candidateProfileId:{in:candidateIds},job:{companyId:company.id}},select:{candidateProfileId:true}});const allowed=[...new Set(valid.map(a=>a.candidateProfileId))];if(allowed.length!==new Set(candidateIds).size)throw new ApiError("Collection contains candidates outside your company pipeline.",403);const result=await prisma.employerCandidateCollection.updateMany({where:{id:collectionId,companyId:company.id},data:{candidateIds:allowed}});if(!result.count)throw new ApiError("Collection not found.",404);await logAuditEvent({userId:s.id,companyId:company.id,action:"CANDIDATE_COLLECTION_UPDATED",resource:`CandidateCollection:${collectionId}`,details:`Candidate count ${allowed.length}`,ipAddress:req.headers.get("x-forwarded-for")||undefined});return NextResponse.json({success:true,candidateIds:allowed});}catch(e){return handleApiError(e);}}
