"use client";
import React,{useState}from"react";
type Q={id:string;questionKey:string;questionText:string;roleTitle:string;skillTags:string[];answerDurationSeconds:number;version:number;isActive:boolean};
export default function RecordedQuestionBankPage(){const[role,setRole]=useState("");const[items,setItems]=useState<Q[]>([]);const[form,setForm]=useState({questionKey:"",roleTitle:"",industry:"",department:"",skillTags:"",questionText:"",answerDurationSeconds:30 as 30|60,difficulty:"BASIC" as const});const[msg,setMsg]=useState("");
 const load=async()=>{if(!role.trim())return;const r=await fetch(`/api/admin/recorded-assessment/questions?roleTitle=${encodeURIComponent(role.trim())}`);const b=await r.json();if(!r.ok){setMsg(b.error||"Unable to load.");return;}setItems(b.questions||[]);setMsg("");};
 const retire=async(id:string)=>{const r=await fetch(`/api/admin/recorded-assessment/questions/${id}`,{method:"DELETE"});const b=await r.json();if(!r.ok){setMsg(b.error||"Unable to retire question.");return;}setItems(x=>x.filter(q=>q.id!==id));setMsg("Question retired. Existing frozen attempts are unchanged.");};
 const add=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/admin/recorded-assessment/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,industry:form.industry||null,department:form.department||null,skillTags:form.skillTags.split(",").map(x=>x.trim()).filter(Boolean)})});const b=await r.json();if(!r.ok){setMsg(b.error||"Unable to add question.");return;}setItems(x=>[b.question,...x]);setMsg(`Question added as version ${b.question.version}.`);};
 return <div className="max-w-6xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold">Recorded Assessment Question Bank</h1><p className="text-sm text-text-secondary mt-1">Curate basic screening questions by role, industry, department and skill. Live attempts use frozen snapshots.</p></div>
 <div className="rounded-3xl border border-outline bg-bg-card p-5 flex flex-wrap gap-3"><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Role title, e.g. React Developer" className="min-h-11 flex-1 min-w-64 rounded-xl border border-outline bg-bg-elevated px-3"/><button onClick={load} className="min-h-11 rounded-full border border-outline px-5 font-bold">Load role bank</button></div>
 <form onSubmit={add} className="rounded-3xl border border-outline bg-bg-card p-5 grid sm:grid-cols-2 gap-4"><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.questionKey} onChange={e=>setForm({...form,questionKey:e.target.value.toLowerCase().trim()})} placeholder="Stable key, e.g. react-hooks-basics" className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/><input required minLength={2} value={form.roleTitle} onChange={e=>setForm({...form,roleTitle:e.target.value})} placeholder="Role title" className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/><input value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})} placeholder="Industry (optional)" className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Department (optional)" className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/><input value={form.skillTags} onChange={e=>setForm({...form,skillTags:e.target.value})} placeholder="Skills, comma separated" className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"/><textarea required minLength={8} value={form.questionText} onChange={e=>setForm({...form,questionText:e.target.value})} placeholder="Basic screening question" className="sm:col-span-2 min-h-24 rounded-xl border border-outline bg-bg-elevated p-3"/><select value={form.answerDurationSeconds} onChange={e=>setForm({...form,answerDurationSeconds:Number(e.target.value) as 30|60})} className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3"><option value={30}>30 seconds</option><option value={60}>60 seconds</option></select><div className="min-h-11 rounded-xl border border-outline bg-bg-elevated px-3 flex items-center text-sm text-text-secondary">Version assigned automatically · Basic screening</div><button className="sm:col-span-2 min-h-11 rounded-full btn-3d-red px-6 font-bold">Add curated question</button></form>
 {msg&&<p role="status" className="text-sm">{msg}</p>}<div className="space-y-3">{items.map(q=><div key={q.id} className="rounded-2xl border border-outline bg-bg-card p-4"><div className="flex justify-between gap-3"><p className="font-bold">{q.questionText}</p><span className="text-xs text-text-secondary">{q.answerDurationSeconds}s · v{q.version}</span></div><p className="text-xs text-text-secondary mt-2">{q.roleTitle} · {q.questionKey}{q.skillTags.length?` · ${q.skillTags.join(" · ")}`:""}</p><button type="button" onClick={()=>void retire(q.id)} className="mt-3 min-h-11 rounded-full border border-outline px-4 text-xs font-bold">Retire from future assessments</button></div>)}</div></div>;
}
